### ISSUE TITLE
Limit on selectable repos?

### ISSUE THREAD

**Issue by lewisnyman** [fiatjaf/jekmentions#1]
It seems like there is a numeric limit on the repos I can select. I can't select my personal site repo: https://github.com/lewisnyman/lewisnyman.co.uk-source

![screen shot 2015-07-12 at 13 55 47](https://cloud.githubusercontent.com/assets/632390/8637856/cff4be98-289d-11e5-822c-0b2aa0b22c3c.jpg)

**Comment by fiatjaf** [comment]
I don't understand this. Can you find some `limit` cause in the GitHub API docs?

**Comment by sknebel** [comment]
I think the endpoint is paginated with 30 entries per page by default. 
https://developer.github.com/v3/#pagination

Simplest change would be to ask for 100 entries per page, cleanest to actually follow the pagination links and request all links.

**Comment by fiatjaf** [comment]
Thank you very much, @sknebel!

I'll close this with https://github.com/fiatjaf/jekmentions/commit/153ad0bf85a1e688430271e8c0f56e6a9b50c80a, but there's still the problem of people with more than 100 repos.

If you're reading this and have more than 100 repos, please edit the HTML manually to add your repo and select it. Asking for a fix in this thread can also work, but may take much more time.
