### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sknebel** [fiatjaf/jekmentions#2]
Hi,

I just stumbled over the entire webmention thing, and I think your project is a clever idea for all the statically hosted sites out there. Is it intended to be Open-Source? If yes, could you add a license, e.g. by including a LICENSE file?

**Comment by fiatjaf** [comment]
Fixed on https://github.com/fiatjaf/jekmentions/commit/62be1b7710f2d6c4b3efd552dc437a9be4820a44
